apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      name: http
      targetPort: 9000
      protocol: TCP
    - port: 9001
      name: console
      targetPort: 9001
      protocol: TCP  
  selector:
    app: minio
