# permissions for end users to edit kubeflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflow-editor-role
rules:
- apiGroups:
  - peach.vmware.com
  resources:
  - kubeflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - peach.vmware.com
  resources:
  - kubeflows/status
  verbs:
  - get
