apiVersion: v1
data:
  profile-name: kubeflow-user-example-com
  user: user@example.com
kind: ConfigMap
metadata:
  name: default-install-config-5cbhhbttg4
  annotations:
    kapp.k14s.io/change-group: apps.kubeflow.org/order-10
    kapp.k14s.io/change-rule: upsert after upserting apps.kubeflow.org/order-9
---
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: kubeflow-user-example-com
  annotations:
    kapp.k14s.io/change-group: apps.kubeflow.org/order-10
    kapp.k14s.io/change-rule: upsert after upserting apps.kubeflow.org/order-9
spec:
  owner:
    kind: User
    name: user@example.com
