#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind": "Service", "metadata": {"name": "istio-ingressgateway", "namespace": "istio-system"}}), expects=1
---
spec:
  type: #@ data.values.service_type
  #@ if data.values.service_type == "LoadBalancer" and data.values.IP_address != "":
  #@overlay/match missing_ok=True
  loadBalancerIP: #@ data.values.IP_address
  #@ end
