#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "centraldashboard", "namespace": "kubeflow"}}), expects=1
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by='name'
      - name: centraldashboard
        image: projects.registry.vmware.com/kubeflow/centraldashboard:v1

#@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "jupyter-web-app-deployment", "namespace": "kubeflow"}}), expects=1
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by='name'
      - name: jupyter-web-app
        image: projects.registry.vmware.com/kubeflow/jupyter-web-app:v1

#@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "notebook-controller-deployment", "namespace": "kubeflow"}}), expects=1
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by='name'
      - name: manager
        image: projects.registry.vmware.com/kubeflow/notebook-controller:v1


#@overlay/match by=overlay.subset({"kind": "ConfigMap", "metadata": {"name": "jupyter-web-app-config-hdc8b8c222", "namespace": "kubeflow"}}), expects=1
---
data:
  spawner_ui_config.yaml: #@ data.read("spawner_ui_config.conf")
