apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: kubeflow
    istio-injection: enabled
  name: kubeflow
  annotations:
    kapp.k14s.io/change-group: apps.kubeflow.org/order-6
    kapp.k14s.io/change-rule: upsert after upserting apps.kubeflow.org/order-5
