apiVersion: v1
kind: Pod
metadata:
  name: kubeflow-worker
  namespace: {{ .Values.tkg.namespace }}
spec:
  volumes:
  - name: config
    configMap:
      name: {{ .Values.carvel.configmap }}
      items:
      - key: values.yaml
        path: values.yaml
  containers:
  - name: kubeflow-worker
    image: {{ .Values.image | default "projects.registry.vmware.com/kubeflow/supervisor-service-worker-pod:0.0.1" }}
    imagePullPolicy: Always
    workingDir: "/app"
    command: ["/bin/bash", "-c", "./worker-entrypoint.sh"]
    env:
      # auth
      - name: vsphere_username
        value: {{ .Values.auth.vsphere_username }}
      - name: vsphere_password
        value: {{ .Values.auth.vsphere_password }}
      # tkg
      - name: vsphere_namespace
        value: {{ .Values.tkg.namespace }}
      - name: vsphere_cluster_name
        value: {{ .Values.tkg.cluster_name }}
      # carvel meta
      - name: carvel_repo
        value: {{ .Values.carvel.repo | default "projects.registry.vmware.com/kubeflow/kubeflow-carvel-repo:0.11" }}
    volumeMounts:
      - mountPath: /app/cfg
        name: config
    resources:
      requests:
        memory: "128Mi"